"""Shared limits for direct AuraPreview editing."""

MAX_INITIAL_PLACEMENTS = 64
MAX_REVISION_OPERATIONS = 128
MAX_TOTAL_PREVIEW_INSTANCES = 1024
MAX_DUPLICATE_COUNT = 64

__all__ = [
    "MAX_DUPLICATE_COUNT",
    "MAX_INITIAL_PLACEMENTS",
    "MAX_REVISION_OPERATIONS",
    "MAX_TOTAL_PREVIEW_INSTANCES",
]
