"""Canonical composition and exports for built-in tool schemas."""
from __future__ import annotations

from typing import Any

from .checklist import TASK_CHECKLIST_TOOL_DEF
from .code_intel import (
    CODE_INTEL_AUDIT_TOOL_DEF,
    CODE_INTEL_DEPENDENTS_TOOL_DEF,
    CODE_INTEL_OUTLINE_TOOL_DEF,
    CODE_INTEL_REFERENCES_TOOL_DEF,
    CODE_INTEL_TOOL_DEFS,
    INSPECT_CODE_TOOL_DEF,
)
from .git import GIT_TOOL_DEFS
from .godot import GODOT_READ_TOOL_DEFS, GODOT_WRITE_TOOL_DEFS
from .memory import PROJECT_MEMORY_TOOL_DEFS
from .plan_review import REVIEW_IMPLEMENTATION_PLAN_TOOL_DEF
from .read import CORE_READ_TOOL_DEFS
from .search import SEARCH_TOOL_DEFS
from .skills import LOAD_SKILLS_TOOL_DEF, READ_SKILL_RESOURCE_TOOL_DEF
from .snapshot import WORKSPACE_SNAPSHOT_TOOL_DEF
from .terminal import DIAGNOSTIC_TOOL_DEF, TERMINAL_TOOL_DEF
from .write import APPLY_PATCH_TOOL_DEF, FILESYSTEM_WRITE_TOOL_DEFS

# Capability modules own the definitions; this module only assembles the
# stable public lists.
READ_TOOL_DEFS: list[dict[str, Any]] = [
    *GODOT_READ_TOOL_DEFS,
    *CORE_READ_TOOL_DEFS,
    *SEARCH_TOOL_DEFS,
    *CODE_INTEL_TOOL_DEFS,
]

WRITE_TOOL_DEFS: list[dict[str, Any]] = [
    *GODOT_WRITE_TOOL_DEFS,
    *FILESYSTEM_WRITE_TOOL_DEFS,
]

__all__ = [
    "APPLY_PATCH_TOOL_DEF",
    "CODE_INTEL_AUDIT_TOOL_DEF",
    "CODE_INTEL_DEPENDENTS_TOOL_DEF", "CODE_INTEL_OUTLINE_TOOL_DEF",
    "CODE_INTEL_REFERENCES_TOOL_DEF", "CODE_INTEL_TOOL_DEFS",
    "CORE_READ_TOOL_DEFS",
    "DIAGNOSTIC_TOOL_DEF", "FILESYSTEM_WRITE_TOOL_DEFS", "GIT_TOOL_DEFS",
    "GODOT_READ_TOOL_DEFS", "GODOT_WRITE_TOOL_DEFS", "INSPECT_CODE_TOOL_DEF",
    "LOAD_SKILLS_TOOL_DEF",
    "PROJECT_MEMORY_TOOL_DEFS", "READ_SKILL_RESOURCE_TOOL_DEF", "READ_TOOL_DEFS",
    "REVIEW_IMPLEMENTATION_PLAN_TOOL_DEF",
    "SEARCH_TOOL_DEFS",
    "TERMINAL_TOOL_DEF",
    "TASK_CHECKLIST_TOOL_DEF", "WORKSPACE_SNAPSHOT_TOOL_DEF", "WRITE_TOOL_DEFS",
]
